Repository octobox/octobox, pull requests merged in 2018-10, with the labels that each got.

#1030 CSS cleanup
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/dark.scss
  app/assets/stylesheets/themes/darkly/_bootswatch.scss
  app/assets/stylesheets/themes/darkly/_variables.scss
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: design, refactor

#1035 Add multiple templates for different kinds of issues
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/support.md
Labels: documentation, misc

#1037 Settings page tweaks and improvements
  app/controllers/users_controller.rb
  app/views/users/edit.html.erb
Labels: enhancement

#1039 Issue 1033
  app/assets/stylesheets/_application.scss
  app/views/notifications/_notification.html.erb
Labels: bug

#1038 Compartmentalise scss to make it more legible
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_badges.scss
  app/assets/stylesheets/_dialogs.scss
  app/assets/stylesheets/_fills.scss
  app/assets/stylesheets/_labels.scss
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_navbar.scss
  app/assets/stylesheets/_notifications.scss
  app/assets/stylesheets/_sidebar.scss
  app/assets/stylesheets/_variables.scss
Labels: misc

#1041 Add the Octobox Roadmap
  docs/README.md
  docs/ROADMAP.md
Labels: documentation

#1040 Fix scrolling behaviours on smaller devices
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_notifications.scss
  app/views/layouts/_footer.html.erb
  app/views/notifications/index.html.erb
  app/views/pages/documentation.html.erb
Labels: bug, design

#1015 Prefill active search query based on filter params
  app/controllers/notifications_controller.rb
  app/models/search.rb
  app/views/layouts/_header.html.erb
  app/views/notifications/_sidebar.html.erb
  lib/search_parser.rb
Labels: refactor

#1046 Fix sidebar scrolling in Firefox
  app/assets/stylesheets/_layout.scss
Labels: bug, design

#1051 Only trigger keyboard shortcuts if on the index page
  app/assets/javascripts/octobox.js
Labels: bug

#1047 Add repo name as title attribute to filter items
  app/helpers/notifications_helper.rb
Labels: enhancement

#1044 added Pull Request statuses fixes #866
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_badges.scss
  app/assets/stylesheets/_fills.scss
  app/assets/stylesheets/_notifications.scss
  app/assets/stylesheets/_variables.scss
  app/controllers/hooks_controller.rb
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/models/search.rb
  app/models/subject.rb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_search-help.html.erb
  app/views/notifications/_sidebar.html.erb
  app/views/shared/_search_prefixes.html.erb
  app/workers/sync_status_worker.rb
  db/migrate/20181002064359_add_status_to_subjects.rb
  db/schema.rb
  docs/INSTALLATION.md
  docs/ROADMAP.md
  lib/octobox/notifications/exclusive_scope.rb
  lib/octobox/notifications/inclusive_scope.rb
  lib/octobox/notifications/sync_repository.rb
  lib/octobox/notifications/sync_subject.rb
  test/controllers/hooks_controller_test.rb
  test/controllers/notifications_controller_test.rb
  test/fixtures/files/status_request.json
  test/fixtures/github_webhooks/status.json
  test/models/notification_test.rb
  test/models/subject_test.rb
Labels: enhancement

#1058 Small tweaks to the visuals for CI status
  app/assets/stylesheets/_badges.scss
  app/views/notifications/_sidebar.html.erb
Labels: design

#1060 Show tooltip on status icons
  app/helpers/notifications_helper.rb
Labels: misc

#1061 Add a rake task to sync app installation data from GitHub
  app/models/app_installation.rb
  app/workers/sync_installation_worker.rb
  lib/tasks/tasks.rake
Labels: misc, octobox.io

#1064 Silent warning when syncing app installations
  app/models/app_installation.rb
Labels: misc

#1065 Document the status filter
  app/views/pages/documentation.html.erb
Labels: documentation

#1073 Fix adding repositories to installations when they already exist in the database
  app/models/app_installation.rb
Labels: bug

#1070 Update cancellation email on terms page
  app/views/pages/terms.html.erb
Labels: misc, octobox.io

#1074 Fix subjectable scope on Notifications
  lib/octobox/notifications/inclusive_scope.rb
  test/models/notification_test.rb
Labels: bug

#1077 Fix some cases of incorrect conversion from params to search query
  app/models/search.rb
  test/models/search_test.rb
Labels: bug

#1076 Fix some missing colors
  app/assets/stylesheets/_fills.scss
  app/assets/stylesheets/_variables.scss
Labels: bug, design

#1078 Prompt users to log into the GitHub App
  app/views/notifications/_login_prompt.html.erb
  app/views/notifications/_notification.html.erb
Labels: enhancement

#1075 Rubocop fixes
  .rubocop.yml
  app/models/notification.rb
  app/models/search.rb
  bin/spring
  config/initializers/simple_form_bootstrap.rb
  lib/page_limiting_octokit_client.rb
  lib/search_parser.rb
  lib/tasks/opencollective.rake
  test/controllers/notifications_controller_test.rb
  test/controllers/users_controller_test.rb
  test/lib/search_parser_test.rb
  test/models/notification_test.rb
  test/models/repository_test.rb
Labels: refactor

#1093 Status webhooks should update subects with combined status result
  app/controllers/hooks_controller.rb
  app/models/app_installation.rb
  app/models/subject.rb
  app/workers/sync_status_worker.rb
  lib/octobox.rb
  lib/octobox/notifications/sync_subject.rb
  test/factories/subject.rb
  test/fixtures/files/status_success.json
  test/models/subject_test.rb
Labels: bug

#1096 Ensure locked field is updated when existing subjects are updated
  lib/octobox/notifications/sync_subject.rb
Labels: bug

#1094 Sync subject body for issues and pull requests
  db/migrate/20181012130339_add_body_to_subjects.rb
  db/schema.rb
  lib/octobox/notifications/sync_subject.rb
Labels: enhancement

#1097 Show first few lines of issue/pr body as title on notification links
  app/models/notification.rb
  app/views/notifications/_notification.html.erb
Labels: enhancement

#1099 Tiny typo fix in notification model test
  test/models/notification_test.rb
Labels: misc

#1117 Sync all subject field when recieving webhook events
  app/models/subject.rb
Labels: bug

#1118 Sync comment_count on subject
  app/models/subject.rb
  db/migrate/20181018095459_add_comments_count_to_subjects.rb
  db/schema.rb
  lib/octobox/notifications/sync_subject.rb
  test/fixtures/files/commit_no_author.json
  test/fixtures/files/release.json
  test/models/subject_test.rb
Labels: enhancement

#1119 Add pinned search count to admin
  app/views/admin/index.html.erb
Labels: misc

#1121 Listen to repository webhook event and sync on trigger
  app/controllers/hooks_controller.rb
  app/models/repository.rb
  app/workers/sync_repository_worker.rb
  test/controllers/hooks_controller_test.rb
  test/fixtures/github_webhooks/repository.json
Labels: misc

#1127 Correctly handle Octokit::Unauthorized errors when updating notifications
  app/models/notification.rb
Labels: misc

#1129 Gracefully handle subject syncing jobs where the notification has been deleted
  app/workers/update_subject_worker.rb
Labels: misc

#1130 Silence github App api warning
  app/models/app_installation.rb
Labels: misc

#1134 Allow syncing of private repository subjects even if can't display them
  app/models/notification.rb
  lib/octobox/notifications/sync_subject.rb
Labels: octobox.io

#1131 Only attempt to update labels and state if subject has been saved
  lib/octobox/notifications/sync_subject.rb
Labels: bug

#1148 Allow configuration of app path for Github Enterprise installs
  lib/octobox/configurator.rb
Labels: misc

#1166 Fix version syntax in docker-compose.yml
  docker-compose.yml
  docs/INSTALLATION.md
Labels: bug

#1095 Sync comments for issues, pull requests and commits
  app/models/comment.rb
  app/models/subject.rb
  app/views/admin/index.html.erb
  db/migrate/20181012132332_create_comments.rb
  db/schema.rb
  lib/octobox.rb
  lib/octobox/configurator.rb
  lib/octobox/notifications/sync_subject.rb
Labels: enhancement

#1168 Fix links in the contributing guide
  docs/CONTRIBUTING.md
Labels: documentation
