Repository octobox/octobox, pull requests merged in 2018-09, with the labels that each got.

#745 Always show read/unread sidebar menu items
  app/views/notifications/_sidebar.html.erb
Labels: enhancement

#854 Store repository_full_name on Subject and setup proper relations with Repository
  app/models/notification.rb
  app/models/repository.rb
  app/models/subject.rb
  db/migrate/20180830145149_add_repository_full_name_to_subjects.rb
  db/schema.rb
  test/models/repository_test.rb
Labels: enhancement

#864 Skip syncing users who don't have an access_token
  app/workers/sync_notifications_worker.rb
Labels: enhancement

#870 Avoid calling sidekiq unless background jobs are enabled
  app/models/user.rb
Labels: bug

#868 Add feature list to Readme
  README.md
Labels: documentation, enhancement

#869 Add feature list to homepage
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/helpers/application_helper.rb
  app/views/pages/home.html.erb
Labels: enhancement

#872 Avoid double sidebar separator when @states contains only a nil key
  app/views/notifications/_sidebar.html.erb
Labels: bug

#875 Push subject syncing to sidekiq if background jobs enabled
  app/models/notification.rb
  app/workers/sync_installation_repositories_worker.rb
  app/workers/sync_installation_worker.rb
  app/workers/sync_label_worker.rb
  app/workers/update_subject_worker.rb
  lib/tasks/tasks.rake
  test/models/notification_test.rb
  test/support/stub_helper.rb
Labels: enhancement

#884 Sync button shouldn't refresh page if sync is happening in background
  app/assets/javascripts/application.js
  app/controllers/notifications_controller.rb
  app/views/notifications/index.html.erb
  test/controllers/notifications_controller_test.rb
Labels: :pencil: work in progress

#890 Update favicons and app icon
  app/assets/images/app-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
Labels: design

#895 Extracted checking for app_token onto User method
  app/controllers/application_controller.rb
  app/models/notification.rb
  app/models/user.rb
  app/views/users/edit.html.erb
Labels: refactor

#896 Eager load notification users before syncin subjets in sidekiq workers
  app/workers/sync_installation_repositories_worker.rb
  app/workers/sync_installation_worker.rb
Labels: performance

#899 Sync repository updates in the background if sidekiq enabled
  app/models/notification.rb
  app/workers/update_repository_worker.rb
  lib/tasks/tasks.rake
Labels: enhancement, performance

#898 Reorder Notification#display_subject? conditions
  app/models/notification.rb
Labels: performance

#897 Move add/remove AppInstallation repository logic from worker to class
  app/models/app_installation.rb
  app/workers/sync_installation_repositories_worker.rb
  app/workers/sync_installation_worker.rb
Labels: refactor

#901 Add Octobox.github_app_client for making API requests as the GitHub App
  Gemfile
  Gemfile.lock
  lib/octobox.rb
  lib/octobox/configurator.rb
Labels: enhancement

#902 Add repository_full_name index on notifications table
  db/migrate/20180910161047_add_repository_full_name_index_to_notifications.rb
  db/schema.rb
Labels: performance

#891 Add sorting to notifications
  app/controllers/notifications_controller.rb
  app/models/search.rb
  app/views/shared/_search_prefixes.html.erb
Labels: enhancement

#905 Bring back #891
  app/controllers/notifications_controller.rb
  app/models/search.rb
  app/views/shared/_search_prefixes.html.erb
Labels: bug

#907 Sync GitHub App installations that a user has access to manage
  app/models/app_installation.rb
  app/models/app_installation_permission.rb
  app/models/user.rb
  app/workers/sync_installation_permissions_worker.rb
  db/migrate/20180911133519_create_app_installation_permissions.rb
  db/schema.rb
Labels: enhancement

#910 Show installed github apps on user settings page
  app/models/app_installation.rb
  app/models/repository.rb
  app/models/user.rb
  app/views/users/edit.html.erb
Labels: enhancement

#911 Don't show full list of repositories with app installed in settings
  app/models/app_installation.rb
  app/views/users/edit.html.erb
Labels: enhancement

#915 Small tweaks to github app settings section
  app/views/users/edit.html.erb
Labels: enhancement

#916 Ignore the docs folder when generating docker images or heroku slugs
  .dockerignore
  .slugignore
Labels: misc

#769 Dark mode
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/dark.scss
  app/assets/stylesheets/light.scss
  app/assets/stylesheets/themes/darkly/_bootswatch.scss
  app/assets/stylesheets/themes/darkly/_variables.scss
  app/assets/stylesheets/themes/default/_variables.scss
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/notifications_helper.rb
  app/views/layouts/application.html.erb
  app/views/notifications/index.html.erb
  app/views/users/edit.html.erb
  config/initializers/assets.rb
  db/migrate/20180810075442_add_theme_to_users.rb
  db/schema.rb
Labels: :pencil: work in progress, design, enhancement, help wanted

#918 Revert "Ignore the docs folder when generating docker images or heroku slugs"
  .dockerignore
  .slugignore
Labels: bug

#920 Fix darkmode svg colors
  app/assets/stylesheets/_application.scss
Labels: design

#823 Show action buttons on hover of notification row
  app/assets/stylesheets/_application.scss
  app/controllers/notifications_controller.rb
  app/views/notifications/_notification.html.erb
  test/controllers/notifications_controller_test.rb
Labels: :pencil: work in progress, enhancement

#929 Add validation of unique urls in subjects table
  app/models/subject.rb
  lib/tasks/tasks.rake
Labels: bug

#924 Fix svg fill color issues
  app/assets/stylesheets/_application.scss
Labels: design, help wanted

#926 Addresses #828 Sync locked details onto subjects
  app/models/notification.rb
  app/models/search.rb
  app/models/subject.rb
  app/views/shared/_search_prefixes.html.erb
  db/migrate/20180913142522_add_locked_to_subject.rb
  db/schema.rb
  test/controllers/notifications_controller_test.rb
Labels: enhancement

#930 Skip edit label webhooks when there are no changes
  app/workers/sync_label_worker.rb
Labels: bug

#931 Refactoring out boolean search prefix method
  app/models/search.rb
Labels: refactor

#937 Use kaminari paginator to calculate @total
  app/controllers/notifications_controller.rb
Labels: performance

#939 Eager load repositories when syncing notifications
  app/services/download_service.rb
Labels: performance

#940 Squash a sneaky n+1 query when running as a github app when calling web_url
  app/controllers/notifications_controller.rb
  app/models/notification.rb
Labels: performance

#941 Add redis and faraday probes to skylight config
  config/environments/production.rb
Labels: misc

#933 Split each sidebar section into it's own unordered list
  app/assets/stylesheets/_application.scss
  app/helpers/application_helper.rb
  app/views/notifications/_sidebar.html.erb
Labels: refactor

#945 Always sync repositories if subjects_enabled?
  app/models/notification.rb
Labels: bug

#946 Remove faraday probe as it's causing errors in sidekiq
  config/environments/production.rb
Labels: bug, octobox.io

#950 Suppress logger output for asset requests in production
  config/environments/production.rb
Labels: misc

#948 Lazy load gemoji gem
  Gemfile
  app/helpers/emoji_helper.rb
Labels: performance

#947 Add inbox:true search prefix
  app/models/search.rb
  app/views/shared/_search_prefixes.html.erb
  test/controllers/notifications_controller_test.rb
Labels: enhancement

#954 Allow more search prefixes to accept multiple arguements
  app/models/notification.rb
  app/models/search.rb
  app/views/notifications/_search-help.html.erb
  test/controllers/notifications_controller_test.rb
  test/factories/label.rb
Labels: enhancement

#956 Delay syncing involved users after webhook event by 1 minute
  app/models/subject.rb
Labels: misc, octobox.io

#943 feature(docker): Adapt Docker image to run sidekiq when enabled
  Dockerfile
  bin/docker-start
  config/Procfile.foreman
Labels: enhancement

#964 Marketplace support
  app/controllers/hooks_controller.rb
  app/controllers/notifications_controller.rb
  app/models/app_installation.rb
  app/models/notification.rb
  app/models/repository.rb
  app/models/subscription_plan.rb
  app/models/subscription_purchase.rb
  app/views/admin/index.html.erb
  app/views/users/edit.html.erb
  app/workers/marketplace_purchase_worker.rb
  config/sidekiq.yml
  db/migrate/20180912120123_create_subscription_plans.rb
  db/migrate/20180912125744_create_subscription_purchases.rb
  db/schema.rb
  lib/tasks/marketplace.rake
Labels: octobox.io

#966 Only speculatively sync users who've not been synced within the last minute
  app/models/subject.rb
  app/models/user.rb
Labels: misc

#967 Avoid enqueueing sidekiq jobs that would be no-ops
  app/models/notification.rb
  test/models/notification_test.rb
  test/support/stub_helper.rb
Labels: refactor

#969 Mark notifications as read on github in the background if sidekiq configured
  app/models/notification.rb
  app/workers/mark_read_worker.rb
Labels: performance

#962 added Bullet gem to detect N+1 queries and unused eager loading
  Gemfile
  Gemfile.lock
  config/initializers/active_record_query_trace.rb
  config/initializers/bullet.rb
Labels: blocked, enhancement

#971 Mute notifications on github in the background if sidekiq configured
  app/models/notification.rb
  app/workers/mute_notifications_worker.rb
Labels: performance

#978 fixes #973 Better handling of renamed/transferred repositories #973
  app/models/repository.rb
  lib/octobox/repository/update_notification_repository_name.rb
  test/models/repository_test.rb
Labels: enhancement

#982 Excludable search prefixes
  app/models/notification.rb
  app/models/search.rb
  lib/search_parser.rb
  test/controllers/notifications_controller_test.rb
  test/lib/search_parser_test.rb
  test/models/repository_test.rb
Labels: enhancement

#983 Remove custom font options from dark theme
  app/assets/stylesheets/themes/darkly/_bootswatch.scss
  app/assets/stylesheets/themes/darkly/_variables.scss
Labels: bug, design

#980 Add a rake task to update old notifications with renamed repositories
  Gemfile.lock
  lib/tasks/tasks.rake
Labels: misc

#994 Gracefully handle jobs that have been enqueud after a notification was deleted
  app/workers/update_repository_worker.rb
Labels: bug

#995 Remove html from readme title
  README.md
Labels: documentation, misc

#997 Don't fire keyboard shortcuts when ctrl/cmd/alt/shift held down
  app/assets/javascripts/application.js
Labels: bug

#999 Remove bootstrap jumbotron usage
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_bootstrap-custom.scss
  app/assets/stylesheets/themes/darkly/_variables.scss
  app/assets/stylesheets/themes/default/_variables.scss
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
Labels: design, refactor

#949 Use libidn to reduce memory usage of addressable gem
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/INSTALLATION.md
Labels: performance

#1001 Use Oj for generating and parsing JSON
  Gemfile
  Gemfile.lock
  app/controllers/hooks_controller.rb
  config/initializers/oj.rb
  test/controllers/notifications_controller_test.rb
  test/lib/page_limiting_octokit_client_test.rb
  test/support/stub_helper.rb
  test/test_helper.rb
Labels: performance

#1002 Revert "Use libidn to reduce memory usage of addressable gem"
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/INSTALLATION.md
Labels: performance

#844 Add visual acceptance tests
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/views/notifications/index.html.erb
  app/views/pages/documentation.html.erb
  lib/octobox/configurator.rb
  test/visual_test_helper.rb
  test/visuals/visual_integration_test.rb
Labels: :pencil: work in progress, design, help wanted

#951 JS reorganization
  app/assets/javascripts/application.js
  app/assets/javascripts/octobox.js
  app/views/notifications/_notification.html.erb
Labels: refactor

#993 Mobile fixes
  app/assets/stylesheets/_application.scss
  app/views/pages/home.html.erb
Labels: :pencil: work in progress, design

#1006 Only show subject author details if present
  app/views/notifications/_notification.html.erb
Labels: bug

#1003 Use yard for generating api docs
  .gitignore
  Gemfile
  Gemfile.lock
  lib/tasks/docs.rake
Labels: bug

#1007 Remove username from header
  app/views/layouts/_header.html.erb
Labels: design

#1008 Notification.archived should default value to true if none or nil passed
  app/models/notification.rb
  test/controllers/notifications_controller_test.rb
Labels: bug

#1011 Add user and org as aliases for owner search prefix
  app/models/search.rb
  test/models/search_test.rb
Labels: enhancement

#960 Search History suggestions fixes #803
  app/assets/javascripts/application.js
  app/assets/javascripts/search_suggestion.js
  app/assets/stylesheets/_application.scss
  app/views/layouts/_header.html.erb
Labels: enhancement

#1014 Small behaviour change to seleting a search history item
  app/assets/javascripts/application.js
  app/assets/javascripts/search_suggestion.js
  app/views/layouts/_header.html.erb
Labels: misc

#1022 Only load notification javascript functions for logged in users
  app/assets/javascripts/octobox.js
Labels: bug

#1024 Avoid redirect loop in notifications#sync
  app/controllers/notifications_controller.rb
Labels: bug

#1025 Embed the users total unread count for the favicon in the index page.
  app/assets/javascripts/octobox.js
  app/controllers/notifications_controller.rb
  app/views/notifications/index.html.erb
Labels: refactor

#1029 Split toggleArchive into seperate functions for archive/unarchive buttons
  app/assets/javascripts/application.js
  app/assets/javascripts/octobox.js
Labels: bug
