Repository octobox/octobox, pull requests merged in 2018-08, with the labels that each got.

#366 Upgrade Bootstrap to 4.0.0
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/helpers/notifications_helper.rb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/layouts/_header.html.erb
  app/views/notifications/_filter-list.html.erb
  app/views/notifications/_help-box.html.erb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_sidebar.html.erb
  app/views/notifications/index.html.erb
  app/views/pages/home.html.erb
  app/views/users/edit.html.erb
Labels: design, enhancement

#731 Show star and fork counts again on homepage
  app/views/pages/home.html.erb
Labels: bug

#730 Run main screenshot through imageoptim, saves 17% filesize
  app/assets/images/screenshot.png
Labels: enhancement

#720 Correctly scroll flexbox sidebar and main contents in firefox
  app/assets/stylesheets/application.scss
Labels: bug, design

#737 Subject -> notifications -> users
  app/models/subject.rb
Labels: enhancement

#748 Fix/721 add momentum scrolling on ios devices
  app/assets/stylesheets/application.scss
Labels: enhancement

#751 Render emoji in labels on active filter menu
  app/views/notifications/_filter-list.html.erb
Labels: bug, design

#746 Remove count from favicon when the unread count becomes zero
  app/assets/javascripts/application.js
Labels: bug

#744 Improve the per-page dropdown menu
  app/assets/stylesheets/application.scss
  app/views/notifications/index.html.erb
Labels: design, enhancement

#750 Set emoji height in labels to same height as text
  app/assets/stylesheets/application.scss
  app/helpers/emoji_helper.rb
  test/helpers/emoji_helper_test.rb
Labels: bug

#619 Encrypt access tokens
  Gemfile
  Gemfile.lock
  app.json
  app/controllers/application_controller.rb
  app/models/user.rb
  db/migrate/20180423185221_add_encrypted_access_token_to_user.rb
  db/schema.rb
  docs/INSTALLATION.md
  lib/octobox/configurator.rb
  test/controllers/sessions_controller_test.rb
Labels: security

#762 Update screenshot on homepage and readme
  README.md
  app/assets/images/screenshot.png
Labels: enhancement

#759 Gracefully handle Octokit::ServerError exceptions caused by 504 response codes
  app/controllers/application_controller.rb
  app/workers/sync_notifications_worker.rb
  lib/tasks/tasks.rake
Labels: bug, enhancement

#772 Improve blankslates
  app/views/notifications/index.html.erb
Labels: design, enhancement

#773 Improve styling on terms and privacy pages
  app/views/pages/privacy.html.erb
  app/views/pages/terms.html.erb
Labels: design, enhancement

#756 Add a filter for unlabelled issues and pull requests
  app/controllers/notifications_controller.rb
  app/models/notification.rb
  app/views/notifications/_sidebar.html.erb
Labels: enhancement

#770 Add ability to filter by bot
  app/controllers/notifications_controller.rb
  app/models/notification.rb
  app/views/notifications/_sidebar.html.erb
Labels: enhancement

#775 Advanced search queries
  app/assets/stylesheets/application.scss
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/models/search.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_search-help.html.erb
  lib/search_parser.rb
  test/controllers/notifications_controller_test.rb
  test/lib/search_parser_test.rb
  test/models/search_test.rb
Labels: :pencil: work in progress, enhancement

#791 Make repo names in notifications table filter by that repo rather than external links
  app/views/notifications/_notification.html.erb
Labels: enhancement

#790 Allow filtering by author and change author links to filter by that user
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/models/search.rb
  app/views/notifications/_filter-list.html.erb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_search-help.html.erb
Labels: enhancement

#798 Sync github_id onto subjects
  app/models/notification.rb
  db/migrate/20180816142404_add_github_id_to_subjects.rb
  db/schema.rb
  test/factories/subject.rb
Labels: enhancement

#761 Sync subject assignees and allow filtering by assignee
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/views/notifications/_filter-list.html.erb
  app/views/notifications/_sidebar.html.erb
  db/migrate/20180809083823_add_assignees_to_subjects.rb
  db/schema.rb
  test/fixtures/files/subject_57.json
Labels: :pencil: work in progress, enhancement

#802 Show bot and unlabelled filters in filter menu when active
  app/helpers/notifications_helper.rb
  app/views/notifications/_filter-list.html.erb
Labels: bug

#781 Sync repository visibility along with subjects
  app/assets/stylesheets/application.scss
  app/controllers/notifications_controller.rb
  app/models/notification.rb
  app/models/repository.rb
  app/views/notifications/_sidebar.html.erb
  db/migrate/20180813150116_create_repositories.rb
  db/schema.rb
  test/controllers/notifications_controller_test.rb
  test/controllers/users_controller_test.rb
  test/fixtures/files/repository.json
  test/integration/routes_test.rb
  test/lib/tasks_test.rb
  test/models/notification_test.rb
  test/support/stub_helper.rb
  test/workers/sync_notifications_worker_test.rb
Labels: :pencil: work in progress, enhancement

#804 Don't block page load whilst loading and parsing javascript
  app/views/layouts/application.html.erb
Labels: enhancement

#783 Repo visibility filter
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/models/search.rb
  app/views/notifications/_filter-list.html.erb
  app/views/notifications/_search-help.html.erb
  app/views/notifications/_sidebar.html.erb
Labels: :pencil: work in progress, enhancement

#805 Add a link to see newer commits on master since your last octobox deploy
  app/views/users/edit.html.erb
Labels: enhancement

#810 Gracefully handle rate limit related errors
  app/controllers/application_controller.rb
  config/locales/en.yml
Labels: enhancement

#807 Enable pg_stat_statements postgres extension
  db/migrate/20180817172203_enable_pg_stat_statements_extension.rb
  db/schema.rb
Labels: enhancement

#819 Don't try to download subjects unless they are one of the four supported types
  app/models/notification.rb
Labels: enhancement

#821 Pin the filter/action bar to the top of the notifications table
  app/assets/stylesheets/application.scss
  app/views/notifications/index.html.erb
Labels: design, enhancement

#827 Use git-merge icon for merged pull requests to match GitHub behaviour
  app/helpers/notifications_helper.rb
Labels: design

#833 Basic admin page
  app/assets/stylesheets/_bootstrap-custom.scss
  app/controllers/admin_controller.rb
  app/views/admin/index.html.erb
  app/views/layouts/_header.html.erb
  config/routes.rb
Labels: enhancement

#832 Respect github_domain config when linking to notification settings
  app/views/notifications/index.html.erb
Labels: enhancement

#840 Revert "Bump pg from 1.0.0 to 1.1.0"
  Gemfile.lock
Labels: bug

#603 User sync in the background
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/controllers/notifications_controller.rb
  app/models/user.rb
  app/views/notifications/index.html.erb
  app/workers/sync_all_user_notifications_worker.rb
  app/workers/sync_notifications_worker.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  config/sidekiq.yml
  db/migrate/20180411201658_add_sync_job_id_to_user.rb
  db/schema.rb
  test/controllers/notifications_controller_test.rb
  test/controllers/sessions_controller_test.rb
  test/lib/tasks_test.rb
  test/models/user_test.rb
  test/support/omniauth.rb
  test/support/sidekiq_helper.rb
  test/test_helper.rb
  test/workers/sync_notifications_worker_test.rb
Labels: enhancement
