Repository octobox/octobox, pull requests merged in 2018-11, with the labels that each got.

#1174 Ignore pending marketplace webhook actions for now
  app/controllers/hooks_controller.rb
Labels: octobox.io

#1176 Fix avatars and urls for bots in thread view
  app/helpers/application_helper.rb
  app/models/comment.rb
  app/models/subject.rb
  app/views/notifications/_thread.html.erb
Labels: bug

#1187 Homepage refresh
  app/assets/stylesheets/_application.scss
  app/assets/stylesheets/_cards.scss
  app/assets/stylesheets/_ribbons.scss
  app/views/pages/_github.html.erb
  app/views/pages/_opencollective.html.erb
  app/views/pages/_ribbon.html.erb
  app/views/pages/home.html.erb
  app/views/pages/pricing.html.erb
Labels: accessibility, design

#1135 Perform initial sync of subjects using an installation token
  app/models/app_installation.rb
  app/models/repository.rb
  app/workers/update_repo_subjects_worker.rb
  config/sidekiq.yml
  test/controllers/hooks_controller_test.rb
  test/controllers/notifications_controller_test.rb
  test/fixtures/files/access_token.json
  test/fixtures/files/comments.json
  test/support/stub_helper.rb
Labels: bug

#1211 Only download status if there's a valid github client available
  app/models/subject.rb
Labels: bug

#1212 Send people to the GitHub Marketplace if MARKETPLACE_URL is present
  lib/octobox/configurator.rb
Labels: octobox.io

#1217 Tweak copy for filters in feature list
  README.md
  app/views/pages/home.html.erb
Labels: documentation

#1216 Enable the GitHub Marketplace pricing option
  app/views/pages/_github.html.erb
Labels: octobox.io

#1227 Skip visual integration tests on travis
  .travis.yml
Labels: misc

#1213 Update documentation
  README.md
  docs/assets/notification-settings.png
Labels: documentation

#1220 Visual review
  app/assets/javascripts/octobox.js
  app/assets/stylesheets/_notifications.scss
  app/assets/stylesheets/themes/darkly/_variables.scss
  app/views/layouts/_header.html.erb
Labels: :pencil: work in progress, accessibility, design

#1228 Confirm deleting notifications
  app/assets/javascripts/octobox.js
  app/views/notifications/_notification.html.erb
Labels: misc

#1232 Show free trials count in admin dashboard
  app/models/subscription_purchase.rb
  app/views/admin/index.html.erb
Labels: misc, octobox.io

#1235 Fix table row border hover bug in chrome by making it 1px wide
  app/assets/stylesheets/_notifications.scss
Labels: bug, design

#1237 Clarify pricing
  app/views/pages/home.html.erb
  app/views/pages/pricing.html.erb
Labels: design, enhancement

#1239 Add more featured orgs to the homepage
  app/helpers/application_helper.rb
Labels: misc, octobox.io

#1241 Fix active star color
  app/assets/stylesheets/_fills.scss
Labels: bug

#1252 The header height is now 63px
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_variables.scss
Labels: bug, design

#1251 Remove padding on bottom of sidebar
  app/assets/stylesheets/_layout.scss
Labels: refactor

#1250 Reduce padding in sidebar
  app/assets/stylesheets/_layout.scss
  app/assets/stylesheets/_sidebar.scss
Labels: design

#1258 Add index on subject_id to comments
  db/migrate/20181119121346_add_index_to_comments.rb
  db/schema.rb
Labels: performance

#1263 Add index on github_id for repositories table
  db/migrate/20181120094340_add_github_id_index_to_repositories.rb
  db/schema.rb
Labels: performance

#1266 Only try to sync comments if the subject has a comment_count > 0
  app/models/subject.rb
Labels: performance

#1268 Switch to travis virtual machine-based runtime
  .travis.yml
Labels: misc

#1269 Order comments by date rather than ID
  app/views/notifications/_thread.html.erb
Labels: bug

#1270 Order comments from oldest to newest
  app/views/notifications/_thread.html.erb
Labels: bug

#1271 Show a spinner when loading a thread view
  app/assets/javascripts/octobox.js
  app/views/notifications/_loading.html.erb
  app/views/notifications/index.html.erb
  app/views/notifications/show.html.erb
Labels: accessibility, enhancement

#1272 Always expand the last comment in a thread
  app/controllers/notifications_controller.rb
  app/models/comment.rb
  app/views/notifications/_thread.html.erb
Labels: enhancement, refactor

#1080 Push notification changes directly to the browser
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/sync.js
  app/assets/stylesheets/_notifications.scss
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/channels/notifications_channel.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/models/subject.rb
  app/views/layouts/application.html.erb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_sidebar.html.erb
  app/views/notifications/_thread.html.erb
  config/application.rb
  config/cable.yml
  config/routes.rb
  docs/INSTALLATION.md
  lib/octobox/configurator.rb
Labels: enhancement

#1278 Use update rather than update_attributes when saving existing repos
  lib/octobox/notifications/sync_repository.rb
Labels: bug

#1282 Involved users should always be ones that haven't been recently synced
  app/models/subject.rb
Labels: bug

#1290 Fix javascript error when opening external subject links
  app/assets/javascripts/application.js
  app/views/notifications/_notification.html.erb
Labels: bug

#1288 Add a linked button to reply on GitHub to bottom of threads
  app/models/subject.rb
  app/views/notifications/_thread.html.erb
Labels: enhancement

#1291 Remove some console.logs from search suggestions js
  app/assets/javascripts/search_suggestion.js
Labels: refactor

#1302 Add paying subscriptions count to admin dashboard
  app/models/subscription_purchase.rb
  app/views/admin/index.html.erb
Labels: misc, octobox.io
