Repository octobox/octobox, pull requests merged in 2019-01, with the labels that each got.

#1410 Reduce pinned search sql query count
  app/views/notifications/_sidebar.html.erb
Labels: performance

#1411 Skip sidebar sql queries when rendering the threadview partial via ajax
  app/controllers/notifications_controller.rb
  app/views/notifications/_thread.html.erb
Labels: performance

#1413 Use full_name field when syncing subjects if available in API response
  app/models/subject.rb
Labels: misc

#1414 Use fast_total to speed up total notification count on homepage.
  app/models/application_record.rb
  app/views/pages/home.html.erb
Labels: performance

#1415 Always sync subjects for open source repositories
  app/models/notification.rb
  app/models/repository.rb
  lib/octobox/notifications/sync_subject.rb
  test/controllers/admin_controller_test.rb
  test/controllers/notifications_controller_test.rb
  test/controllers/pinned_searches_controller_test.rb
  test/controllers/users_controller_test.rb
  test/integration/routes_test.rb
Labels: enhancement

#1416 Only attempt to download subjects if there's a github_client available
  lib/octobox/notifications/sync_subject.rb
Labels: misc

#1420 Only sync subject comments made after the most recent one
  app/models/subject.rb
  test/support/stub_helper.rb
Labels: performance

#1422 Allow limiting syncing of open source subjects before a given date.
  docs/INSTALLATION.md
  lib/octobox/configurator.rb
  lib/octobox/notifications/sync_subject.rb
Labels: misc

#1423 Show different app install prompt for notifications from oss repos
  app/views/notifications/_app_prompt.html.erb
Labels: misc

#1439 Only attempt to load comments in thread view if subject is present
  app/controllers/notifications_controller.rb
Labels: bug

#1440 Shorten the check to see if we're running on octobox.io to `Octobox.io?`
  app/models/app_installation.rb
  app/models/repository.rb
  app/views/admin/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/notifications/_notification.html.erb
  app/views/pages/documentation.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_repo_scope_modal.html.erb
  app/views/users/edit.html.erb
  config/routes.rb
  lib/octobox.rb
  lib/tasks/marketplace.rake
Labels: misc, octobox.io

#1443 Support bot:false search prefix
  app/controllers/notifications_controller.rb
  app/models/search.rb
  lib/octobox/notifications/inclusive_scope.rb
  test/controllers/notifications_controller_test.rb
Labels: enhancement

#1459 Add index to subjects table on repository_full_name
  db/migrate/20190114174802_add_repository_full_name_index_to_subjects.rb
  db/schema.rb
Labels: performance

#1460 Remove unused scope from Subject
  app/models/subject.rb
Labels: misc, refactor

#1464 Only update repository records if changed when syncing
  app/models/notification.rb
  test/models/notification_test.rb
Labels: performance

#1466 Avoid scheduling a sync of an involved user who's currently syncing
  app/models/subject.rb
Labels: performance

#1468 Only sync repository and subject on a notification if it's changed
  app/models/notification.rb
Labels: performance

#1479 Use subject comment counter cache where available
  app/controllers/notifications_controller.rb
  app/views/notifications/_notification.html.erb
  app/views/notifications/_thread.html.erb
  test/controllers/notifications_controller_test.rb
  test/factories/subject.rb
Labels: performance

#1483 Change queues of some sidekiq jobs
  app/workers/mark_read_worker.rb
  app/workers/mute_notifications_worker.rb
  app/workers/sync_github_app_authorization_worker.rb
  app/workers/sync_installation_permissions_worker.rb
  app/workers/sync_installation_repositories_worker.rb
  app/workers/sync_installation_worker.rb
  app/workers/sync_repository_worker.rb
  config/sidekiq.yml
Labels: misc

#1486 Only download notifications that have been updated since last_synced_at
  app/models/notification.rb
  app/services/download_service.rb
  test/models/notification_test.rb
Labels: refactor

#1488 Fix syncing of subject and comment body
  app/models/subject.rb
  test/fixtures/files/subject_56.json
  test/models/subject_test.rb
Labels: bug

#1493 Disable actioncable logs in production
  config/environments/production.rb
Labels: octobox.io

#1498 Comment counts should only be shown if display_subject is true
  app/views/notifications/_notification.html.erb
Labels: misc, octobox.io

#1503 Remove visual test dependencies from Travis CI config
  .travis.yml
Labels: misc, refactor

#1504 Sync read/unread state of all notifications every time
  app/services/download_service.rb
  test/workers/sync_notifications_worker_test.rb
Labels: enhancement

#1514 Add tooltip names of free trial and paid account names to admin
  app/views/admin/index.html.erb
Labels: misc, octobox.io

#1484 Update thread when receiving notification updates and new comments
  Gemfile
  Gemfile.lock
  app/assets/javascripts/channels/comments.js
  app/assets/javascripts/channels/notifications.js
  app/assets/javascripts/channels/sync.js
  app/channels/comments_channel.rb
  app/channels/notifications_channel.rb
  app/models/comment.rb
  app/models/notification.rb
  app/views/notifications/_comment.html.erb
  app/views/notifications/_comments.html.erb
  app/views/notifications/_thread.html.erb
  app/views/notifications/_thread_subject.html.erb
  test/channels/comments_channel_test.rb
  test/channels/notifications_channel_test.rb
  test/controllers/notifications_controller_test.rb
Labels: enhancement

#1528 Link to blogpost about upcoming pricing changes
  app/views/layouts/_header.html.erb
Labels: octobox.io

#1532 Header alert shouldn't try to open a modal
  app/views/layouts/_header.html.erb
Labels: bug, octobox.io

#1533 Octobox.io admin fix
  app/views/admin/index.html.erb
Labels: bug, misc, octobox.io

#1536 Only show google analytics privacy policy section if it's enabled.
  app/views/pages/privacy.html.erb
Labels: octobox.io

#1433 Require paid plan for notifications of private repos on octobox.io
  app/assets/stylesheets/_notifications.scss
  app/models/notification.rb
  app/views/layouts/_header.html.erb
  app/views/notifications/_notification.html.erb
  lib/octobox/notifications/sync_subject.rb
  test/models/notification_test.rb
Labels: :pencil: work in progress, octobox.io

#1540 Gracefully handle notifications that have no associated user
  app/views/notifications/_app_prompt.html.erb
Labels: bug

#1544 Refactor notification partial
  app/views/notifications/_notification.html.erb
Labels: refactor

#1548 Fix display of private notifications where user hasn't paid
  app/views/notifications/_notification.html.erb
Labels: bug, octobox.io

#1549 Switch to skylight alpha release to enable job tracking
  Gemfile
  Gemfile.lock
Labels: misc, octobox.io, performance

#1551 Only call sync_involved_users explicitly after syncing a subject
  app/models/subject.rb
  test/controllers/notifications_controller_test.rb
  test/support/omniauth.rb
Labels: performance

#1552 Eager load data for rendering a notification row when pushing_to_channel
  app/models/subject.rb
Labels: performance

#1553 Allow more names in private_repositories_enabled?
  app/models/subscription_plan.rb
Labels: octobox.io

#1428 Add coverage to Subject.sync
  test/models/subject_test.rb
Labels: :pencil: work in progress
