Repository octobox/octobox, pull requests merged in 2019-02, with the labels that each got.

#1564 Update ruby to 2.6.1
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/INSTALLATION.md
Labels: dependencies, misc

#1562 Add subject tests
  test/models/subject_test.rb
Labels: refactor

#1563 Synchronous open collective donation journey
  app/controllers/application_controller.rb
  app/controllers/open_collective_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/sessions_controller.rb
  app/models/subscription_purchase.rb
  app/views/pages/_opencollective.html.erb
  config/routes.rb
  config/secrets.yml
  db/migrate/20190207110533_add_oc_transactionid_to_subscription_purchases.rb
  db/schema.rb
  lib/octobox/open_collective.rb
  test/controllers/open_collective_controller_test.rb
  test/fixtures/files/oc_error.json
  test/fixtures/files/oc_transaction.json
Labels: enhancement, octobox.io

#1566 Stub more api requests in oc controller tests
  test/controllers/open_collective_controller_test.rb
Labels: misc

#1571 Fix free trial typo
  app/views/users/edit.html.erb
Labels: misc

#1578 Disable downgrading open collective subscribers for now
  lib/octobox/open_collective.rb
Labels: octobox.io

#1619 Add hirefire configuration
  Gemfile
  Gemfile.lock
  config/initializers/hirefire_resource.rb
  config/secrets.yml
Labels: octobox.io

#1620 Skip the test that fails 50% of the time
  test/controllers/notifications_controller_test.rb
Labels: misc

#1523 Post comments directly to a subject from Octobox
  app/assets/javascripts/channels/comments.js
  app/assets/javascripts/octobox.js
  app/controllers/notifications_controller.rb
  app/models/app_installation.rb
  app/models/comment.rb
  app/models/repository.rb
  app/models/subject.rb
  app/models/user.rb
  app/views/notifications/_reply.html.erb
  app/views/notifications/_thread.html.erb
  app/workers/comment_worker.rb
  config/routes.rb
  docs/INSTALLATION.md
  docs/ROADMAP.md
  test/controllers/notifications_controller_test.rb
  test/factories/comment.rb
  test/factories/user.rb
  test/fixtures/files/new_comment.json
  test/models/user_test.rb
  test/workers/comment_worker_test.rb
Labels: enhancement

#1625 Use fast_total on admin page to speed up rendering on large instances
  app/views/admin/index.html.erb
Labels: performance

#1626 Fix login redirect loop in Safari
  app/controllers/sessions_controller.rb
  test/controllers/sessions_controller_test.rb
Labels: bug

#1631 Add default searches to new users
  app/models/user.rb
  test/controllers/notifications_controller_test.rb
  test/controllers/pinned_searches_controller_test.rb
Labels: help wanted

#1641 Update app installation sync rake task
  lib/tasks/tasks.rake
Labels: misc
